### ISSUE TITLE
Step 1 points to invalid remote repository (git@github.com:uport-project/budilbox.git)

### ISSUE THREAD

**Issue by inaeem** [uport-project/buidlbox#6]
Update Step 1 text 
from  
-------- Step 1 --------
git clone git@github.com:uport-project/budilbox.git budilbox ; cd budilbox
to 
-------- Step 1 --------
git clone git@github.com:uport-project/buidlbox.git buildbox ; cd buildbox

**Comment by KamesCG** [comment]
Thank you 🙇- fixed.
